version: '3'

services:
    musicbot:
        build: ./
        image: musicbot
        container_name: ${NAME:-musicbot}
        volumes:
            - ./config:/jmb/config
        restart: unless-stopped
